# Generated by Django 4.2.5 on 2023-09-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_cartitems_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Количество товара в корзине'),
        ),
    ]
