# Generated by Django 4.2.5 on 2023-09-24 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='productuser',
            name='last_name',
        ),
    ]
